name: BTB
main: com.iteamcn.BTB.BTB
version: 1.1.0
author: OVAmach
depend: [PowerNBT]

commands:
  btb:
      description:
      usage:
permissions:
  btb.use:
      default: true
  btb.admin:
      default: op
      children:
           btb.get: true
           btb.change: true